### ISSUE TITLE
unable to load materials from model_normalized.mtl

### ISSUE THREAD

**Issue by WangHaoyuuu** [cangumeli/ROCA#6]
skipping vacant point sample ('02933112', '37e5fcf70007bc26788f926f4d51e733')...

WARNING - 2022-05-30 21:59:28,861 - obj - unable to load materials from: model_normalized.mtl

WARNING - 2022-05-30 21:59:28,868 - obj - specified material (material_52_24)  not loaded!

**Comment by cangumeli** [comment]
Material warnings come from trimesh, since we do not use materials we do not have to care them.

Vacant point sample print has a different source. It is a debugging print that is not very important. It says we have a point cloud sample in the pickle file that does not exist in our images. It should not cause any error.
